Src/routes/atestados_alunos.py
from flask import Blueprint, Flask, redirect, request, render_template, url_for, current_app, send_file
from utils.helpers import *
from uuid import uuid4
from io import BytesIO
from datetime import datetime, timezone


atestados_alunos = Blueprint('atestados_alunos', __name__)

def formatar_data(data):
    return "-".join(data.split('-')[::-1])

@atestados_alunos.route('/atestados_alunos', methods=['POST','GET'])
def index():

    if not current_app.config['RA_ATUAL']:
        return redirect(url_for('auth.login'))

    atestados = []

    for atestado in usuario_atual()['atestados']:
        atestados.append(usuario_atual()['atestados'][atestado])

    return render_template('atestados_alunos.html', atestados = atestados, usuario = usuario_atual())

@atestados_alunos.route('/enviar_atestados', methods =['POST', 'GET'])
def enviar():
    usuario = usuario_atual()
    if not current_app.config['RA_ATUAL']:
        return redirect(url_for('auth.login'))
    
    if request.method == 'POST':
        pdf = request.files['pdf']
        c_afastamento = request.form['c_afastamento']
        f_afastamento = request.form['f_afastamento']
    
    os.makedirs(f"uploads/{current_app.config['RA_ATUAL']}", exist_ok=True)

    pdf_path = f'uploads/{current_app.config['RA_ATUAL']}/{pdf.filename}'
    caminho_pdf = os.path.join(pdf_path)

    pdf.save(caminho_pdf)
    cadastros = carregar_alunos()

    if 'num_atestados' in usuario.keys():
        usuario['num_atestados'] += 1
    else:
        usuario['num_atestados'] = 1

    for i, cadastro in enumerate(cadastros):
        if cadastro['ra'] == usuario['ra']: # ou current_app.config['RA_ATUAL']
           
            if 'num_atestados' in cadastros[i]:
                cadastros[i]['num_atestados'] += 1
            else:
                cadastros[i]['num_atestados'] = 1

            data_criado = str(datetime.now(timezone.utc)).split(' ')[0]

            cadastros[i]['atestados'][f'atestado_{usuario['num_atestados']}'] = {'pdf': pdf_path,
                                                                                'id': str(uuid4()),
                                                                                'data_criado': formatar_data(data_criado),
                                                                                'status': 'Não Verificado',
                                                                                'c_afastamento': formatar_data(c_afastamento),
                                                                                'f_afastamento': formatar_data(f_afastamento)}
    
    salvar_aluno(cadastros)
    return redirect(url_for('atestados_alunos.index'))

@atestados_alunos.route('/download_atestados/<string:id>', methods =['POST', 'GET'])
def download(id):
    usuario = usuario_atual()
    atestado = pegar_atestado(id=id)

    nome_arquivo = f'Atestado {usuario['atestados'][atestado]['data_criado']} {usuario['nome']}.pdf'
    caminho = usuario['atestados'][atestado]['pdf']
    with open(caminho, "rb") as file:
        pdf_bytes = BytesIO(file.read())
    return send_file(pdf_bytes,
                     mimetype= 'application/pdf',
                     as_attachment=True,
                     download_name=nome_arquivo)

@atestados_alunos.route('/delete/<string:id>')
def delete(id):
    usuario = usuario_atual()

    try:
        os.remove(usuario['atestados'][pegar_atestado(id)]['pdf'])
    except:
        pass

    cadastros = carregar_alunos()
    for cadastro in cadastros:
        if cadastro['ra'] == usuario['ra']:
              cadastro['atestados'].pop(pegar_atestado(id))
    salvar_aluno(cadastros)

    return redirect(url_for('atestados_alunos.index'))

@atestados_alunos.route('/abrir_atestados/<path:pdf>')
def abrir_atestados(pdf):
    return send_file(pdf, mimetype='application/pdf', as_attachment=False)

Src/routes/atestados_professor.py
from flask import Blueprint, Flask, redirect, request, render_template, url_for, current_app, send_file
from io import BytesIO
from utils.helpers import *

atestados_professor = Blueprint('atestados_professor', __name__)

CADASTROS_JSON = "data/usuarios.json"

@atestados_professor.route('/index', methods=['GET', 'POST'])
def index():
    usuarios = []
    with open(CADASTROS_JSON, 'r', encoding='UTF-8') as file:
        usuarios = json.load(file)
        
    if request.method == 'POST':
        pesquisa = request.form['Pesquisar']
        classificar = request.form['classificar']
        
        usuarios_filtrados = [usuario for usuario in usuarios if pesquisa in usuario['ra'] or pesquisa.lower() in usuario['nome'].lower()]

        if classificar == 'alfabetica':
            usuarios_filtrados = sorted(usuarios_filtrados, key=lambda x: x['nome'].lower())


        return render_template("atestados_professor.html", usuarios=usuarios_filtrados)
    return render_template('atestados_professor.html', usuarios=usuarios)

@atestados_professor.route('/abrir_atestados/<path:pdf>')
def abrir_atestados(pdf):
    return send_file(pdf, mimetype='application/pdf', as_attachment=False)

@atestados_professor.route('/download_atestados/<string:id>', methods =['POST', 'GET'])
def download(id):
    usuario = usuario_atual()
    atestado = pegar_atestado(id=id)

    nome_arquivo = f'Atestado {usuario['atestados'][atestado]['data_criado']} {usuario['nome']}.pdf'
    caminho = usuario['atestados'][atestado]['pdf']
    with open(caminho, "rb") as file:
        pdf_bytes = BytesIO(file.read())
    return send_file(pdf_bytes,
                     mimetype= 'application/pdf',
                     as_attachment=True,
                     download_name=nome_arquivo)


@atestados_professor.route('/verificar/<string:id>/<string:ra>/<string:status>')
def verificar(id, ra, status):
    
    with open(CADASTROS_JSON, 'r', encoding='utf-8') as file:
        usuarios = json.load(file)

    usuario_atual = {}
    position = 0
    for i, usuario in enumerate(usuarios):
        if usuario['ra'] == ra:
            usuario_atual = usuario
            position = i

    atestado_atual = ""
    for atestado in usuario_atual.get('atestados'):
        if usuario_atual.get('atestados')[atestado]['id'] != id:
            continue
        atestado_atual = atestado
        break
    
    usuarios[position].get('atestados')[atestado_atual]['status'] = status

    with open(CADASTROS_JSON, 'w', encoding='utf-8') as file:
        json.dump(usuarios, file, indent=4, ensure_ascii=False)

    return redirect(url_for('atestados_professor.index'))

Src/routes/auth.py
from flask import Blueprint, Flask, redirect, request, render_template, url_for, current_app
import os, json
from utils.helpers import salvar_aluno, carregar_alunos

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['POST', 'GET'])
def login():

    if current_app.config['RA_ATUAL'] != '':
        return redirect(url_for('atestados_alunos.index'))

    if request.method == 'POST':
        ra = request.form['RA']
        password = request.form['password']

        usuarios = carregar_alunos()

        for usuario in usuarios:
            if usuario['ra'] == ra and usuario['senha'] == password:
                current_app.config['RA_ATUAL'] = usuario['ra']
                return redirect(url_for('atestados_alunos.index'))
    
    return render_template("login_aluno.html")


@auth.route('/login_professor', methods=['GET', 'POST'])
def login_professor():
    if request.method == 'POST':
        senha = request.form.get('senha')

        if senha == current_app.config['SENHA_PROF']:
            return redirect(url_for('atestados_professor.index'))
        
    return render_template('login_professor.html')


@auth.route('/cadastro_aluno', methods=['POST', 'GET'])
def cadastro_aluno():

    if request.method == 'POST':
        dados = {'nome': request.form['nome'],
                 'ra': request.form['ra'],
                 'senha': request.form['senha'],
                 'num_atestados': 0,
                 'atestados': {},
                 'equipe': 'Nenhuma',
                 'função': 'DevTeam',
                 "notas": {"Proatividade": [], "Autonomia": [], "Colaboração": [], "Entrega de Resultados": [], "Comentários": []}}


        alunos = carregar_alunos()

        for aluno in alunos:
            if aluno['ra'] == dados['ra']:
                return redirect(url_for('auth.cadastro_aluno'))
        
        alunos.append(dados)
        salvar_aluno(alunos)

        return redirect(url_for("auth.login"))

    return render_template('cadastro_aluno.html')

@auth.route('/sair')
def sair():
    current_app.config['RA_ATUAL'] = ''
    current_app.config['SCRUM_LOGADO'] = False
    return redirect(url_for('auth.login'))

Src/routes/scrum.py
from flask import Blueprint, Flask, redirect, request, render_template, url_for, current_app
from utils.helpers import *

scrum = Blueprint('scrum', __name__)

def render_with_info():
    if equipe_atual():
        equipe = carregar_equipes()[equipe_atual()]
    else:
        equipe = {}

    return render_template('scrum.html', logado = current_app.config['SCRUM_LOGADO'], 
                        dados_usuario = usuario_atual(),
                        alunos = carregar_alunos(),
                        equipe = equipe,
                        pegar_valor = pegar_valor,
                        pegar_notas = pegar_notas)

@scrum.route('/scrum')
def index():
    if not current_app.config['RA_ATUAL']:
        return redirect(url_for('auth.login'))

    return render_with_info()


@scrum.route('/avaliar_membro/<string:ra>')
def avaliar_membro(ra):
    return render_template('avaliação.html', membro=pegar_membro(ra))


@scrum.route('/finalizar/<string:ra>', methods=['GET', 'POST'])
def finalizar(ra):
    if request.method == 'POST':
        dados = request.form.to_dict()
        
        membros = carregar_alunos()
        avaliado = pegar_membro(ra)

        for nota in avaliado.get('notas'):
            for nota_avaliador in dados:
                if nota.lower() == nota_avaliador:
                    for i, membro in enumerate(membros):
                        if membro.get('ra') == ra:
                            membros[i]['notas'][nota].append([current_app.config['RA_ATUAL'], dados.get(nota_avaliador)])
                            break
        salvar_aluno(membros)

    return redirect(url_for('scrum.index'))

@scrum.route('/notas_usuario')
def notas_usuario():
    return render_template('notas_usuario.html', membro  = usuario_atual(), equipe = equipe_atual())

Src/routes/scrum_master.py
from flask import Blueprint, Flask, redirect, request, render_template, url_for, current_app, flash
from utils.helpers import *

scrum_master = Blueprint('scrum_master', __name__)


def render_with_info():

    if equipe_atual():
        equipe = carregar_equipes()[equipe_atual()]
    else:
        equipe = {}

    return render_template('scrum_master.html', logado = current_app.config['SCRUM_LOGADO'], 
                        dados_usuario = usuario_atual(),
                        alunos = carregar_alunos(),
                        equipe = equipe,
                        pegar_valor = pegar_valor)

@scrum_master.route('/scrum_master', methods=['GET', 'POST'])
def index():

    if not current_app.config['RA_ATUAL']:
        return redirect(url_for('auth.login'))

    return render_with_info()

@scrum_master.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        senha = request.form['senha']

        alunos = carregar_alunos()


        if senha == current_app.config['SENHA_SCRUM']:
            current_app.config['SCRUM_LOGADO'] = True
            mudar_valor(current_app.config['RA_ATUAL'], 'função', 'Scrum Master')
    
    return render_with_info()

@scrum_master.route('/definir_nome', methods=['GET', 'POST'])
def definir_nome():
    if request.method == 'POST':

        nome_equipe = request.form['nome-equipe']

        equipes = carregar_equipes()

        for equipe in equipes:
            if equipe == nome_equipe:
                return render_with_info()

        mudar_valor(current_app.config['RA_ATUAL'], 'equipe', nome_equipe)

        equipes[nome_equipe] = {'num_membros': 1, "avaliação": False, 'membros': [usuario_atual()['ra']]}
        salvar_equipe(equipes)

    return redirect(url_for('scrum_master.index'))


@scrum_master.route('/adicionar_membro', methods=['GET', 'POST'])
def adicionar_membro():

    if request.method == 'POST':
        mudar_valor(request.form['ra-aluno'], 'equipe', usuario_atual()['equipe'])
        mudar_valor(request.form['ra-aluno'], 'função', request.form['função'])

        equipes = carregar_equipes()
        equipes[equipe_atual()]['membros'].append(request.form['ra-aluno'])
        equipes[equipe_atual()]['num_membros'] = len(equipes[equipe_atual()]['membros'])
        salvar_equipe(equipes)

        return redirect(url_for('scrum_master.index'))


@scrum_master.route('/abrir_avaliação')
def abrir_avaliação():
    
    equipe_usuario = equipe_atual()
    equipes = carregar_equipes()

    for equipe in equipes:
        if equipe_usuario == equipe:
            equipes[equipe]['avaliação'] = True
    
    salvar_equipe(equipes)

    alunos = carregar_alunos()

    for ra in equipes[equipe_usuario].get('membros'):
        for i, aluno in enumerate(alunos):
            if aluno.get('ra') == ra:
                for nota in aluno.get('notas'):
                    alunos[i]['notas'][nota] = []
    salvar_aluno(alunos)

    return redirect(url_for('scrum_master.index'))

@scrum_master.route('/fechar_avaliação')
def fechar_avaliação():
    equipe_usuario = equipe_atual()
    equipes = carregar_equipes()

    for equipe in equipes:
        if equipe_usuario == equipe:
            equipes[equipe]['avaliação'] = False
    
    salvar_equipe(equipes)

    alunos = carregar_alunos()

    for ra in equipes[equipe_usuario].get('membros'):
        for i, aluno in enumerate(alunos):
            if aluno.get('ra') == ra:
                for nota in aluno.get('notas'):

                    div = len(aluno['notas'][nota]) if aluno['notas'][nota] else 1
                    if nota != "Comentários" and type(aluno['notas'][nota]) != float:
                        alunos[i]['notas'][nota] = round(sum([int(x[1]) for x in aluno['notas'][nota]])/div, 2)
    salvar_aluno(alunos)


    return redirect(url_for('scrum_master.index'))

# DEBUG

@scrum_master.route('/debug')
def debug():
    for aluno in carregar_alunos():
        mudar_valor(aluno['ra'], 'função', 'DevTeam')
        mudar_valor(aluno['ra'], 'equipe', 'Nenhuma')
    salvar_equipe({})
    return redirect(url_for('auth.login'))

Src/templates/atestados_alunos.html
{% extends 'base.html' %}


{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/atestados_alunos.css') }}">
{% endblock %}


{% block body %}
    <div class="container">
        <div class="atestados">
            <h1>Gerenciador de Atestados</h1>

            {% if not atestados %}
                <h2>Você ainda não enviou nenhum atestado.</h2>
            {% else %}

            <table  border=1 frame=box rules=all class="tabela-atestados" >
            
                <tr>
                    <th>Data de Emissão</th>
                    <th>PDF</th>
                    <th>Ações</th>
                    <th>Ínicio do Afastamento</th>
                    <th>Fim do Afastamento</th>
                    <th>Status</th>
                </tr>
                
                {% for atestado in atestados %}
                    <tr class="item">
                        <td> {{ atestado.get('data_criado') }} </td>
                        <td><a href="{{ url_for('atestados_alunos.abrir_atestados', pdf=atestado.pdf) }}" target="_blank">Abrir</a></td>
                        <td><a href='/atestados_alunos/delete/{{atestado.id}}'>Apagar</a>
                            <a href="/atestados_alunos/download_atestados/{{atestado.id}}">Baixar</a>
                        </th>
                        <td>{{ atestado.c_afastamento }}</td>
                        <td>{{ atestado.f_afastamento }}</td>
                        <td>{{ atestado.status }}</td>
                    </tr>
                {% endfor %}
            </table>
            {% endif %}

        </div>
        <div class="form">
        <h2>Adicionar Atestado</h2>
        <form action='/atestados_alunos/enviar_atestados', method="POST" enctype="multipart/form-data" accept-charset="UTF-8">
            <input type='file' name='pdf' accept='application/pdf' class='upload-input' required>
            Afastado de <input type='date' name='c_afastamento'> até <input type='date' name="f_afastamento">
    
            <input type='submit' name='Adicionar Atestado'>
        </form>
        </div>
    </div>

{% endblock %}

Src/templates/atestados_professor.html
{% extends 'base.html' %}

{% block head %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/atestados_professor.css') }}">
{% endblock %}

{% block body %}
    <nav class="search-container">
        <form action="/atestados_professor/index" method="POST" accept-charset="UTF-8">
            <div id="pesquisa">
                <input type="text" placeholder="Pesquisar Nome/RA" name="Pesquisar">
                <button type="submit"> <i class="fa fa-search"></i></button>
            </div>

            <div id="classificação">
                <label for="classificar">Classificar por:</label>
                <select name="classificar">
                    <option value="upload">Data de Upload</option>
                    <option value="i_afastamento">Ínicio do Afastamento</option>
                    <option value="f_afastamento">Fim do Afastamento</option>
                    <option value="alfabetica">Ordem Alfabética</option>
                </select>
            </div>

        </form>
    </nav>
    

    <section class="resultado-pesquisa">
        {% for usuario in usuarios %}
            {% for atestado in usuario.get("atestados") %}
                <article class="item-pesquisa">
                    <h3>Nome: {{ usuario.nome }}</h3>
                    <h3>RA: {{ usuario.ra }}</h3>
                    {% if usuario.get('atestados').get(atestado).status == "Não Verificado" %}
                        <h3>Status:
                            <a href="{{ url_for('atestados_professor.verificar', id=usuario.get('atestados').get(atestado).id, ra=usuario.ra, status='Deferido')}}">Deferir</a>
                            <a href="{{ url_for('atestados_professor.verificar', id=usuario.get('atestados').get(atestado).id, ra=usuario.ra, status='Indeferido')}}">Indeferir</a>
                        </h3>
                    {% else %}
                        <h3>Status: <a href="{{ url_for('atestados_professor.verificar', id=usuario.get('atestados').get(atestado).id, ra=usuario.ra, status='Não Verificado')}}">
                            {{ usuario.get('atestados').get(atestado).status }}
                        </a></h3>    
                    {% endif %}
                    <h3>Data de Upload: {{ usuario.get('atestados').get(atestado).data_criado }}</h3>
                    <h3>Ínicio do Afastamento: {{ usuario.get('atestados').get(atestado).c_afastamento}} </h3>
                    <h3>Fim do Afastamento: {{ usuario.get('atestados').get(atestado).f_afastamento}} </h3>
                    <a href="{{ url_for('atestados_professor.abrir_atestados', pdf=usuario.get('atestados').get(atestado).pdf) }}" target="_blank">Abrir PDF</a>
                    <a href="{{ url_for('atestados_professor.download', id=usuario.get('atestados').get(atestado).id, ra=usuario.ra) }}">Baixar PDF</a><br>
                    </article>
            {% endfor %}
        {% endfor %}
    </section>
{% endblock %}

Src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://fonts.googleapis.com/css?family=Roboto Slab' rel='stylesheet'>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% block head %}{% endblock %}
</head>
<body>
    <nav class="topnav"> 
        <a href="{{ url_for('auth.login') }}">ÁREA DOS ALUNOS ▼</a>
        <a href="{{ url_for('auth.login_professor') }}">ÁREA DE PROFESSORES ▼</a>
        <a href="{{ url_for('scrum.index') }}">EQUIPE SCRUM ▼</a>
        <a href="{{ url_for('scrum_master.index') }}">SCRUM MASTER ▼</a>
        <a href="{{ url_for('auth.sair') }}">SAIR</a>
    </nav>
    {% block body %}{% endblock %}
</body>
</html>

Src/templates/cadastro_aluno.html
{% extends 'base.html' %}

{% block head%}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/cadastro.css') }}">
{% endblock %}

{% block body%}
    <div class='cadastro'>
        <form action="/auth/cadastro_aluno" method="POST" accept-charset="UTF-8">
            <h1>Cadastro de Alunos</h1>
            
            <h3>Nome de Usuário: </h3>
            <input type="text" name="nome" required><br>
            
            <h3>RA do Aluno: </h3>
            <input type="text" name="ra" required><br>
            
            <h3>Senha: </h3>
            <input type="password" name="senha" required><br>

            <input type="submit" value="Confirmar Cadastro"><br>
        </form>
    </div>
{% endblock %}

Src/templates/index.html
{% extends 'base.html' %}

{% block head %}
    <title>Página Inicial</title>
    <link rel="stylesheet" href="../static/css/index.css">
{% endblock %}

{% block body %}
    <h1>Acesse como: </h1>
    <div class="corpo-home"> 
        
        <a href="{{ url_for('auth.login') }}">
            <button>Aluno</button>
        </a>

        <a href="{{url_for('auth.login_professor')}}">
            <button>Professor</button>
        </a>

        <a href="{{url_for('auth.login')}}">
            <button>Equipe Ágil</button>
        </a>

    </div>
{% endblock %}

Src/templates/login_aluno.html
{% extends 'base.html' %}

{% block head %}
    <title>Página Inicial</title>
    <link rel="stylesheet" href="../static/css/login.css">
{% endblock %}

{% block body %}
    <div class="main-content">
        <div class="login-container">
            <h2>Login Aluno</h2>
            <form action="/auth/login" method="POST" accept-charset="UTF-8">
                <label>RA</label>
                <input type="text" name="RA">
                
                <label>Senha</label>
                <input type="password" name="password">
                
                <input type="submit" value="Login">

                <p>
                    Ainda não possui uma conta?
                    <a href="{{ url_for('auth.cadastro_aluno') }}">Cadastre-se!</a>
                </p>
            </form>
        </div>
    </div> 
{% endblock %}

Src/templates/login_professor.html
{% extends 'base.html'%}

{% block head %}
    <title>Login Professor</title>
    <link rel="stylesheet" href="../static/css/login.css">
{% endblock %}

{% block body %}
    <div class="main-content">
        <div class="login-container">
            <h2>Login Professor</h2>

            <form action="{{ url_for('auth.login_professor') }}" method="POST">
                <label for="senha">Senha</label>
                <input name="senha" id="senha" type="password" required>
                
                <input type="submit" value="Acessar">
            </form>
        </div>
    </div>
{% endblock %}

Src/templates/scrum.html
{% extends 'base.html' %}


{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/scrum.css') }}">
{% endblock %}


{% block body %}

    {% if dados_usuario.equipe == 'Nenhuma' %}
        <div class="não-logado">
            <h1>Avaliação da Equipe Scrum</h1>
            
            <h2>Você não está em uma equipe ainda. Aguarde que o Scrum Master da sua equipe te cadastre!</h2>
        </div>
    {% else %}
        <section class="container">

            {% if not equipe.avaliação and dados_usuario.notas.get('Proatividade') %}
                <h1>Equipe {{dados_usuario.equipe}} - {{equipe.num_membros}} Integrante(s) - <a href="{{ url_for('scrum.notas_usuario')}}">Suas Notas</a></h1>
            {% else %}
                <h1>Equipe {{dados_usuario.equipe}} - {{equipe.num_membros}} Integrante(s)</h1>
            {% endif %}
            <article class="lista-de-membros">
                    {% for membro in equipe.membros %}
                        {% if membro != dados_usuario.ra %}
                           <div class="membro">
                                <h2>{{pegar_valor(membro, 'nome')}} / {{membro}}</h2> 
                                <h2 class="função">{{pegar_valor(membro, 'função')}}</h2>
                                <div class="notas">

                                    {% for nota in pegar_notas(membro) %}
                                        {% if nota != 'Comentários' %}
                                            {% if not pegar_notas(membro).get(nota) is sequence %}
                                                <h3>{{nota}}: {{pegar_notas(membro).get(nota)}}</h3>
                                            {% else %}
                                                <h3>{{nota}}: 0</h3>
                                            {% endif %}
                                        {% endif %}
                                    {% endfor %}
                                
                                {% set notas = [] %}
                                {% for tipo_nota in pegar_notas(membro).values() %}
                                        {% if tipo_nota is sequence %}
                                            {% for valor in tipo_nota %}
                                                {% set notas = notas.append(valor[0]) %}
                                            {% endfor %}
                                        {% endif %}
                                {% endfor %}
                                {% if equipe.avaliação and not dados_usuario.ra in notas %}
                                    <h3><a href="/scrum/avaliar_membro/{{membro}}" id="avaliar">Avaliar Membro</a></h3>
                                {% endif %}
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </article>

        </section>

    {% endif %}
{% endblock %}

Src/templates/scrum_master.html
{% extends 'base.html' %}


{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/scrum_master.css') }}">
{% endblock %}


{% block body %}

    {% if not logado %}
    <div class="login-container">
        <h2>Login Scrum Master</h2>

        <form action="/scrum_master/login" method="post" accept-charset="UTF-8">
            
            <label for="senha">Senha</label>
            <input type="password" name="senha">

            <input type="submit" name="logar" placeholder="Acessar">

        </form>

    </div>
    {% else %}

        {% if dados_usuario.equipe == 'Nenhuma' %}

        <div class="login-container">
            <h2>Nome da sua equipe: </h2>
            
            <form action="/scrum_master/definir_nome" method='post' accept-charset="UTF-8">
                <input type="text" name="nome-equipe">
                <input type="submit" name="confirmar" placeholder="confirmar">
            </form>

        </div>
        {% else %}

        <section class="container">
        <h1>Equipe <a href="{{url_for('scrum_master.definir_nome')}}">{{dados_usuario.equipe}}</a> - {{equipe.num_membros}} Integrante(s)</h1>   
        
            <article class="lista-de-membros">
                {% for membro in equipe.membros %}

                    <div class="membro">
                        <h2>{{pegar_valor(membro, 'nome')}} - {{pegar_valor(membro, 'função')}}</h2>
                        <h2>RA: {{pegar_valor(membro, 'ra')}}</h2>
                    </div>

                {% endfor %}

            </article>

            <div class="adicionar-membro">
                <h2>Adicionar Membro: </h2>

                <form action="/scrum_master/adicionar_membro" method="POST" accept-charset="UTF-8">
                    <label for="ra-aluno">Membro: </label>
                    <select name="ra-aluno" required>
                        <option value="" disabled selected hidden>Escolha um aluno</option>
                        {% for aluno in alunos %}
                            {% if aluno.equipe == 'Nenhuma' %}
                                <option value="{{aluno.ra}}">{{aluno.nome}} - {{aluno.ra}}</option>
                            {% endif %}
                        {% endfor %}
                    </select>

                    <label for="função">Função: </label>
                    <select name="função" required>
                        <option value="DevTeam">DevTeam</option>
                        <option value="Scrum Master">Scrum Master</option>
                        <option value="PO">Product Owner</option>
                    </select><br>
                    
                    <input type="submit" value="Adicionar">

                </form>
            </div>
        </section>

        <div class="avaliação">
            
            <script>

                function alerta_abrir() {
                  let confirmation = confirm("Abrir o período de avaliação apagará todas as notas\n" +
                    "anteriores. Tem certeza de que deseja abrir as avaliações?")
                  if (confirmation) {
                    window.location.href = '{{url_for("scrum_master.abrir_avaliação")}}'
                  } 
                }

                function alerta_fechar() {
                  let confirmation = confirm("Alguns membros provavelmente ainda não terminaram\n" +
                    "de avaliar. Tem certeza de que deseja fechar as avaliações?")
                  if (confirmation) {
                    window.location.href = '{{url_for("scrum_master.fechar_avaliação")}}'
                  } 
                }



            </script>
    
            {% if equipe.avaliação == False %}
                <h1><a onclick="alerta_abrir()" id="abrir-avaliação">Abrir período de Avaliações.</a></h1>
            {% else %}
                <h1><a onclick="alerta_fechar()" id="fechar-avaliação">Fechar Avaliações</a></h1>
            {% endif %}


        </div>

        {% endif %}
    {% endif %}

{% endblock %}